
version: '3.8'

services:
  api-flask:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: main.py
      FLASK_ENV: development
      FLASK_DEBUG: 1
      FLASK_PORT: 5000
    volumes:
      - .:/api-flask